#!/usr/bin/env python3

import json
from functools import cached_property
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler
from http.server import HTTPServer
from urllib.parse import parse_qsl, urlparse
from urllib.parse import parse_qs

class WebRequestHandler(BaseHTTPRequestHandler):

    def print_info(self):
        adr, port = self.client_address
        url = urlparse(self.path)
        params = dict(parse_qsl(url.query))

        print('Source:')
        print(f'\tIP: {adr}')
        print(f'\tPort: {port}')

        print(f'Method: {self.command}')
        print(f'Protocol: {self.protocol_version}')
        print(f'url: {url.path}')

        print('Parameters:')
        for name, value in params.items():
            print(f'\t{name}: {value}')

        print('Headers:')
        for name in self.headers:
            for value in self.headers.get_all(name):
                print(f'\t{name}: {value}')
        
        self.print_data()
        print('----------------------------------------\n')


    def print_data(self):
        content_length = self.headers.get('Content-Length')
        if content_length is None: return
        content_length = int(content_length)

        print('----------------------------------------')
        data = None
        try:
            data = self.rfile.read(content_length).decode('utf8')
        except:
            data = self.rfile.read(content_length).hex()
        print(data)

    def do_GET(self):
        self.print_info()

    def do_POST(self):
        self.print_info()

    def do_DELETE(self):
        self.print_info()

    def do_PUT(self):
        self.print_info()

    def do_HEAD(self):
        self.print_info()


if __name__ == "__main__":
    port = 8000
    address = "0.0.0.0"
    print(f'Starting server on: {address}:{port}')
    server = HTTPServer((address, port), WebRequestHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print('Exiting...')
